
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <pybind11/functional.h>
#include <pybind11/numpy.h>

#include "guiderCentroid.h"
//#include "GDS.h"

namespace py = pybind11;


// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// <litgen_glue_code>  // Autogenerated code below! Do not edit!

// </litgen_glue_code> // Autogenerated code end
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE END !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!



PYBIND11_MODULE(guiderCentroid, m) 
{
    // using namespace guiderCentroid;  // NON!

    // !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    // <litgen_pydef> // Autogenerated code below! Do not edit!
    ////////////////////    <generated_from:guiderCentroid.h>    ////////////////////
    auto pyClassguiderCentroid =
        py::class_<guiderCentroid>
            (m, "guiderCentroid", "")
        .def(py::init<>()) // implicit default constructor
        .def_readwrite("roi_count", &guiderCentroid::roiCount, "")
        .def("measure_centroid",
            &guiderCentroid::measureCentroid, py::arg("roi_number"))
        .def("start_processing",
            &guiderCentroid::startProcessing, py::arg("pixel_source"))
        .def("stop_processing",
            &guiderCentroid::stopProcessing, py::arg("pixel_source"))
        .def("start_guiding",
            &guiderCentroid::startGuiding)
        .def("stop_guiding",
            &guiderCentroid::stopGuiding)
        .def_readwrite("guiding_active", &guiderCentroid::guidingActive, "")
        .def_readwrite("processing_active", &guiderCentroid::processingActive, "")
//        .def_readwrite("gds_location", &guiderCentroid::gdsLocation, "")
//        .def_readonly("gds_partition", &guiderCentroid::gdsPartition, "")
//        .def_readwrite("gds_state", &guiderCentroid::gdsState, "")
//        .def_readwrite("gds_series", &guiderCentroid::gdsSeries, "")
        ;
    ////////////////////    </generated_from:guiderCentroid.h>    ////////////////////

    // </litgen_pydef> // Autogenerated code end
    // !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE END !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
}
