
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <pybind11/functional.h>
#include <pybind11/numpy.h>

#include "guiderProcessor.h"
#include "GDS.h"

namespace py = pybind11;


// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// <litgen_glue_code>  // Autogenerated code below! Do not edit!

// </litgen_glue_code> // Autogenerated code end
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE END !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!



PYBIND11_MODULE(guiderProcessor, m) {
    // using namespace guiderProcessor;  // NON!

    // !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    // <litgen_pydef> // Autogenerated code below! Do not edit!
    ////////////////////    <generated_from:guiderProcessor.h>    ////////////////////
    auto pyClassguiderProcessor =
        py::class_<GDS::guider::guiderProcessor>
            (m, "guiderProcessor", "")
        .def(py::init<const char *, const GDS::LocationSet &>(),
            py::arg("partition"), py::arg("locs"))
        .def_readwrite("gds_rois", &GDS::guider::guiderProcessor::gdsROIS, "")
        ;
    ////////////////////    </generated_from:guiderProcessor.h>    ////////////////////

    // </litgen_pydef> // Autogenerated code end
    // !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE END !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
}
