
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <pybind11/functional.h>
#include <pybind11/numpy.h>

#include "net/ipv4/Buffer.hh"
#include "net/ipv4/Datagram.hh"

#include "gds/LocationSet.hh"
#include "gds/SeriesMetadata.hh"
#include "gds/StateMetadata.hh"
#include "gds/RawStamp.hh"
#include "gds/Subscriber.hh"
#include "GDS.h"

namespace py = pybind11;


// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// <litgen_glue_code>  // Autogenerated code below! Do not edit!

// </litgen_glue_code> // Autogenerated code end
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE END !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


PYBIND11_MODULE(guiderGDS, m) 
{
    // using namespace GDS;  // NON!

    // !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    // <litgen_pydef> // Autogenerated code below! Do not edit!
    ////////////////////    <generated_from:GDS.h>    ////////////////////
    auto pyClassSubscriber =
        py::class_<GDS::Subscriber>
            (m, "Subscriber", "");

    { // inner classes & enums of Subscriber
        auto pyClassSubscriber_ClassStats =
            py::class_<GDS::Subscriber::Stats>
                (pyClassSubscriber, "Stats", "")
            .def(py::init<>())
            .def_readwrite("stamps", &GDS::Subscriber::Stats::stamps, "")
            .def_readwrite("err_xfer", &GDS::Subscriber::Stats::err_xfer, "")
            .def_readwrite("err_size", &GDS::Subscriber::Stats::err_size, "")
            .def_readwrite("err_miss_beg", &GDS::Subscriber::Stats::err_miss_beg, "")
            .def_readwrite("err_miss_end", &GDS::Subscriber::Stats::err_miss_end, "")
            ;
    } // end of inner classes & enums of Subscriber

    pyClassSubscriber
        .def(py::init<const char *, const GDS::LocationSet &>(),
            py::arg("partition"), py::arg("locs"))
        .def("wait",
            &GDS::Subscriber::wait)
        .def("abort",
            &GDS::Subscriber::abort)
        .def("__bool__",
            &GDS::Subscriber::operator bool)
        .def("stats_clear",
            &GDS::Subscriber::stats_clear)
        .def("stats",
            &GDS::Subscriber::stats, py::arg("loc"))
        .def("stamps",
            &GDS::Subscriber::stamps, py::arg("loc"))
        .def("err_xfer",
            &GDS::Subscriber::err_xfer, py::arg("loc"))
        .def("err_size",
            &GDS::Subscriber::err_size, py::arg("loc"))
        .def("err_miss_beg",
            &GDS::Subscriber::err_miss_beg, py::arg("loc"))
        .def("err_miss_end",
            &GDS::Subscriber::err_miss_end, py::arg("loc"))
        ;

    { // <namespace Stream>
        py::module_ pyNsStream = m.def_submodule("stream", "");
    } // </namespace Stream>
    ////////////////////    </generated_from:GDS.h>    ////////////////////

    // </litgen_pydef> // Autogenerated code end
    // !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE END !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
}
